<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login Help_ctl00ContentPlaceHolder1lo_bbd03c</name>
   <tag></tag>
   <elementGuidId>d1ddbc8c-492e-419e-a70c-fc8d4344e6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4462b348-2aa9-40b9-8f28-cb695b28939a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a0652a8c-3890-4759-943a-4391ad72aa97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$loginform$signInButton</value>
      <webElementGuid>f9bfc0a8-4f4a-4fce-a805-dbe10ad9ff63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>8c8db53e-65ef-42c3-a7f3-0fbdb04c5f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$loginform$signInButton&quot;, &quot;&quot;, false, &quot;&quot;, &quot;https://www.alarm.com/web/Default.aspx&quot;, false, false))</value>
      <webElementGuid>b3ec9441-7ae6-4fe3-9d6b-158e292f0808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInButton</value>
      <webElementGuid>65a20868-3186-4d08-bd2e-189b4a7d90ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Login to your account.</value>
      <webElementGuid>c92f80af-2613-4aea-ab54-28f80bf848d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-sign-in</value>
      <webElementGuid>7362a32d-2cc8-4feb-99a7-c38ef1966b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Logging In...</value>
      <webElementGuid>986896f7-3948-47b4-868a-68e3c5f0f396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInButton&quot;)</value>
      <webElementGuid>b689e29f-4f40-4d6e-8f55-f78aee7f40f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInButton']</value>
      <webElementGuid>42a7cfdc-9540-4c05-abb4-12522a433756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_loginform_loginFormControl']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>026e38c2-72b3-4445-9d67-a86c189c712e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>38372ac0-a926-4f1a-bbb3-5a4436c6649e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$loginform$signInButton' and @id = 'signInButton' and @title = 'Login to your account.']</value>
      <webElementGuid>004868ef-e95c-4640-a0ba-7d18aa6a1bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
