<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Settings  Alarm.com (Internal) has l_056185_1</name>
   <tag></tag>
   <elementGuidId>3da76f06-61f4-4a70-b423-8d9d724805ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ember621']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ember621</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa2a826a-88f5-42f9-8ebb-edf2ea45110c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember621</value>
      <webElementGuid>ca36258a-4e95-440e-8cde-c97be73bd772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-iframe ember-view</value>
      <webElementGuid>18c25d1a-7db8-4b75-80a1-cc51c280c9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/web/Video/SettingsOverview_V2.aspx</value>
      <webElementGuid>725ffb0a-5d6e-4a05-a562-651f987311e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember621&quot;)</value>
      <webElementGuid>c15f23e1-172f-4f97-a927-1e343d1da1e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ember621']</value>
      <webElementGuid>ffb63511-19c5-4d8e-a5a5-e1391e5657f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-content']/div[2]/iframe</value>
      <webElementGuid>8c253901-16e9-4077-a129-d9f004957e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5688b8db-a3ac-452b-a07d-a90f5370c6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ember621' and @src = '/web/Video/SettingsOverview_V2.aspx']</value>
      <webElementGuid>d26c230c-db5e-46f9-9176-815476983355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
