<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Settings  Alarm.com (Internal) has l_056185</name>
   <tag></tag>
   <elementGuidId>f0e34387-6de6-49b7-9981-12e15e3707c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember621</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ember621']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>83d3f0ae-8ccd-4e67-ae5d-6c324589e101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember621</value>
      <webElementGuid>7ed2e78f-b68b-428d-9ab1-9ff7fae1e1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-iframe ember-view</value>
      <webElementGuid>357bba88-dff2-4d8a-8226-2eef7fb55420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/web/Video/SettingsOverview_V2.aspx</value>
      <webElementGuid>224296b9-c0a1-423e-bb32-fcbc123e8909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember621&quot;)</value>
      <webElementGuid>839e49f3-fb4a-4e0f-a653-b4fbb4f9ec07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ember621']</value>
      <webElementGuid>859ae7f3-7329-47e7-b041-e088916c45f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-content']/div[2]/iframe</value>
      <webElementGuid>949eb654-cc9f-4e8e-8cc7-9d375fdc185b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c4ca4e80-5fdb-4366-8bfa-6bd7db02e7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ember621' and @src = '/web/Video/SettingsOverview_V2.aspx']</value>
      <webElementGuid>7ed2fa90-a612-4f7e-b246-58c3f2939393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
